### ISSUE TITLE
SoftKeyboard.exe won't run

### ISSUE THREAD

**Issue by bendelathouwer** [MeLight/soft-keyboard#1]
Dear

SoftKeyboard.exe will not run , as far as I can see it shuts down straight away.

Wisth best regards Ben

**Comment by MeLight** [comment]
Hi friend, run in command line - you will see help message and instructions how to run.

**Comment by MeLight** [comment]
@bendelathouwer 
Hi friend, run in command line - you will see help message and instructions how to run.

**Comment by bendelathouwer** [comment]
@MeLight 

How do I do that? bit of a computer nerd here so sorry for the dumb questions

with best regards Ben
